name: Tests
on: [push, pull_request]
jobs:
  test:
    name: test-libjrt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and update dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build and install libjrt
        run: |
          make
          make install
      - name: Test and cleanup
        run: |
          make test
          make clean
          make uninstall
